#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
#      - add_ssh_keys:
#          fingerprints: ""
      - run: terraform init
      - run: terraform plan
  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
#      - add_ssh_keys:
#          fingerprints:
      - run: terraform init
      - run: terraform apply -auto-approve
  openshift:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: terraform init
      - run: terraform apply -auto-approve
      - run: make openshift
  destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: terraform init
      - run: terraform destroy -auto-approve

workflows:
  version: 2
  build:
    jobs:
      - build
#  apply:
#    jobs:
#      - apply
#    triggers:
#      - schedule:
#          cron: "0 0 * * *"
#          filters:
#            branches:
#              only:
#                - bespin
#  openshift:
#    jobs:
#      - openshift
#    triggers:
#      - schedule:
#          cron: "20 0 * * *"
#          filters:
#            branches:
#              only:
#                - bespin
  destroy:
    jobs:
      - destroy
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - bespin
