#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: echo $FINGER_PRINTS
      - run: terraform init
      - run: terraform plan
  destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: terraform init
      - run: terraform destroy -auto-approve

workflows:
  version: 2
  build:
    jobs:
      - destroy
  destroy:
    jobs:
      - destroy
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - bespin
