#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: terraform init
      - run: terraform plan
  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: terraform init
      - run: terraform apply -auto-approve
  openshift:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: terraform init
      - run: make openshift
  destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: terraform init
      - run: terraform destroy -auto-approve

workflows:
  version: 2
  build:
    jobs:
      - build
  apply:
    jobs:
      - apply
    triggers:
      - schedule:
          cron: "0 23 * * *"
          filters:
            branches:
              only:
                - master
  openshift:
    jobs:
      - openshift
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
  destroy:
    jobs:
      - destroy
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - master
